apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/swathireddy73/Argocd.git' # your repo
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true            # Delete resources that are removed from Git
      selfHeal: true         # Auto-correct out-of-sync resources
    syncOptions:
      - CreateNamespace=true   # Create namespace if missing
